config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users,
             path: "session",
             path_names: { sign_in: "login", sign_up: "signup", sign_out: "logout", password: "password", unlock: "unlock" }

  resources :families
  resources :forests do
    resources :plants
  end

  root to: "forests#index"
end

app/models/plant.rb
# == Schema Information
#
# Table name: plants
#
#  id          :bigint           not null, primary key
#  name        :string
#  common_name :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  forest_id   :bigint           not null
#
class Plant < ApplicationRecord
  belongs_to :forest

  validates :common_name, presence: true
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_forest
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def index

  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @forest = Forest.find(params[:forest_id])
    @plant = @forest.plants.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @forest = Forest.find(params[:forest_id])
    @plant = @forest.plants.new(plant_params)

    if @plant.save
      redirect_to forest_plants_path(@forest.id), notice: _('Plant was successfully added.')
    else
      render :new
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    if @plant.update(plant_params)
      redirect_to forest_plant_path(@forest, @plant), notice: _('Plant was successfully updated.')
    else
      render :edit
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    redirect_to forest_plants_url(@forest), notice: 'Plant was successfully removed.'
  end

  private

  def set_forest
    @forest = Forest.find(params[:forest_id])
  end

  def set_plant
    @plant = Plant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def plant_params
    params.require(:plant).permit(:name, :common_name)
  end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.slim
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

= f.input :common_name

app/views/plants/edit.html.slim
- content_for :header, "Edit Plant Details"

= simple_form_for @plant,
                  url: forest_plant_path(@forest, @plant) do |f|
  = render "form", f: f
  = f.button :submit

= link_to 'Show', forest_plant_path(@forest, @plant)
= link_to 'Back', forest_plants_path(@forest)

app/views/plants/index.html.slim
- content_for :header do
  h1 = _("Plants")

- if @forest.plants.any?
  table
    thead
      th Name
      th Botanical name
      th &nbsp;
    tbody
      - @forest.plants.each do |plant|
        tr
          td
            = link_to plant.common_name,
                      forest_plant_path(@forest, plant)
          td TODO
- else
  = _("No plants yet. Add one below.")

<br>

= link_to _("Add a plant to this project"),
          new_forest_plant_path(@forest),
          class: "hollow primary button"

app/views/plants/new.html.slim
- content_for :breadcrumbs do
  - breadcrumb "Forests", forests_path
  - breadcrumb @forest.name, forest_path(@forest)
  - breadcrumb "Add plant", new_forest_plant_path(@forest)

- content_for :header do
  h1 = _("Add plant")

= simple_form_for @plant,
                  url: forest_plants_path do |f|
  = render "form", f: f
  = f.button :submit

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @plant.common_name %>
</p>

<%= link_to 'Edit', edit_forest_plant_path(@forest, @plant) %> |
<%= link_to 'Back', forest_plants_path(@forest) %>