config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users,
             path: "session",
             path_names: { sign_in: "login", sign_up: "signup", sign_out: "logout", password: "password", unlock: "unlock" }

  resources :families
  resources :forests do
    resources :plants
  end

  root to: "forests#index"
end

app/models/forest.rb
# == Schema Information
#
# Table name: forests
#
#  id          :bigint           not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  latitude    :decimal(, )
#  longitude   :decimal(, )
#  drawn_items :jsonb
#
class Forest < ApplicationRecord
  belongs_to :user
  has_many :plants
end

app/controllers/forests_controller.rb
class ForestsController < ApplicationController
  before_action :set_forest, only: [:show, :edit, :update, :destroy]

  def index
    @forests = current_user.forests.all
  end

  def show
  end

  def new
    @forest = current_user.forests.new
  end

  def edit
  end

  def create
    @forest = current_user.forests.new(forest_params)

    respond_to do |format|
      if @forest.save
        format.html { redirect_to @forest, notice: 'Forest was successfully created.' }
        format.json { render :show, status: :created, location: @forest }
      else
        format.html { render :new }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @forest.update(forest_params)
        format.html {
          puts "HTML"
          redirect_to @forest, notice: 'Forest was successfully updated.'
        }
        format.json {
          puts "JSON"
          render :show, status: :ok, location: @forest
        }
      else
        format.html { render :edit }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @forest.destroy
    respond_to do |format|
      format.html { redirect_to forests_url, notice: 'Forest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_forest
    @forest = current_user.forests.find(params[:id])
  end

  def forest_params
    params
      .require(:forest)
      .permit!
      # .permit(
      #   :drawn_items,
      #   :name
      # )
  end
end

app/helpers/forests_helper.rb
module ForestsHelper
end

app/views/forests/_form.html.erb
<%= simple_form_for(@forest) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save Project" %>
  </div>
<% end %>

app/views/forests/edit.html.erb
<h1>Edit Project Details</h1>

<%= render 'form', forest: @forest %>

<%= link_to 'Show', @forest %> |
<%= link_to 'Back', forests_path %>

app/views/forests/index.html.slim
.grid-x.grid-margin-x
  - @forests.each do |forest|
    .cell.small-6.medium-4.large-4
      .card
        .card-divider
          h3 = link_to forest.name, forest
        .card-section
          .small.button-group
            = link_to _("View"), forest_path(forest), class: "hollow secondary button"
            = link_to _("Edit"), edit_forest_path(forest), class: "hollow secondary button"

= link_to _("New project"),
          new_forest_path,
          class: "hollow secondary button"

app/views/forests/new.html.erb
<h1>New Project</h1>

<%= render 'form', forest: @forest %>

<%= link_to 'Back', forests_path %>

app/views/forests/show.html.slim
h1 = @forest.name

h2 = _("Map")

#map(data-controller="map" data-target="map.map" data-map-token="#{ENV['MAPBOX_TOKEN']}" data-map-latitude="#{@forest.latitude}" data-map-longitude="#{@forest.longitude}" data-map-update-url="#{forest_url(@forest)}" data-map-drawn-items="#{@forest.drawn_items}" style="width: 100%; height: 30rem")

.spacer--vertical--2

h2 = _("Plants")

- if @forest.plants.any?
  ul
    - @forest.plants.each do |plant|
      li = link_to plant.common_name, forest_plant_path(@forest, plant)

div
  = link_to _("Add plant"),
            new_forest_plant_path(@forest),
            class: "button button--new"

ul
  li = link_to _("Edit Project Details"), edit_forest_path(@forest)
  li = link_to _("Back"), forests_path